--- 
branch: master
cache: 
  directories: 
    - node_modules
deploy: 
  - 
    provider: script
group: edge
install: 
  - "npm install"
language: node_js
node_js: 
  - "8"
script: "chmod +x ./deploy.sh && ./deploy.sh"
services: mongodb
skip_cleanup: true
sudo: false
true: ~
